### ISSUE TITLE
Error executing http method durring Authorization

### ISSUE THREAD

**Issue by Euklios** [flytreeleft/nexus3-keycloak-plugin#43]
I am trying to set up nexus using keycloak authentication, but are running into an HTTP error.

![image](https://user-images.githubusercontent.com/19554209/77967808-2fe80200-72e6-11ea-8132-3c97f067ba88.png)

## Environment
Keycloak version: 9.0.2
Nexus version: OSS 3.22.0-02
Plugin version: [current master](https://github.com/flytreeleft/nexus3-keycloak-plugin/tree/b9770748062a8c6a3b78852fa13229e01f9d2b23)
Keycloak is backed by UCS (LDAP)

## Reproduce
1. Running in the cloned repository
2. `cd docker`
3. `docker build -t nexus-oss/nexus3:latest -f Dockerfile ..`
4. Create new folder nexus (outside of the git-repository) and place the attached `docker-compose.yml` and `keycloak.json` inside
5. `docker-compose up -d`
6. Follow the default setup as described in the readme

## Attachments
- [nexus.txt](https://github.com/flytreeleft/nexus3-keycloak-plugin/files/4405807/nexus.txt) Client exporte
- [nexus.log](https://github.com/flytreeleft/nexus3-keycloak-plugin/files/4405817/log.log)
- docker-compose.yml
```yml
version: "3.4"

services:
  nexus:
    image: nexus-oss/nexus3:latest
    volumes:
      - data:/nexus-data
      - ./keycloak.json:/opt/sonatype/nexus/etc/keycloak.json:ro
    networks:
      - nginx
    restart: always

volumes:
  data:

networks:
  nginx:
    external:
      name: nginx
```
- keycloak.json
```json
{
  "realm": "Realm",
  "auth-server-url": "$(server-url)",
  "ssl-required": "all",
  "resource": "nexus",
  "verify-token-audience": true,
  "credentials": {
    "secret": "$(secret)"
  },
  "confidential-port": 0,
  "policy-enforcer": {}
}
```
