### ISSUE TITLE
how to use SSO with oauth2-proxy

### ISSUE THREAD

**Issue by Hokwang** [flytreeleft/nexus3-keycloak-plugin#54]
Hi,

My env is
kubernetes on baremetal servers 
use ingress-nginx, keycloak (with openid idp), oauth2-proxy (keycloak-gatekeeper archived and this include that feature).

I follow your readme and can log in using keycloak account and set group permission successfully.

Now I want to set SSO, 
Can you let me know how to do this using oauth2-proxy and ingress-nginx?

I think I can get x-auth-request-access-token, x-auth-request-email, x-auth-request-preferred-username,
but nexus does not recognize I guess.

**Comment by Hokwang** [comment]
here's oauth2-proxy(https://github.com/oauth2-proxy/oauth2-proxy) helm chart(stable/oauth2-proxy)'s my values.yaml.
```yaml
image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "latest"

extraArgs:
  silence-ping-logging: "true"
  provider: "oidc"
  redirect-url: "https://my.company.net/oauth2/callback"
  oidc-issuer-url: "https://my.company.net/keycloak-stage/realms/test"
  login-url: "https://my.company.net/keycloak-stage/realms/test/protocol/openid-connect/auth"
  redeem-url: "https://my.company.net/keycloak-stage/realms/test/protocol/openid-connect/token"
  validate-url: "https://my.company.net/keycloak-stage/realms/test/protocol/openid-connect/userinfo"
  scope: "openid profile email"
  insecure-oidc-allow-unverified-email: "true"

  keycloak-group: "user"
  email-domain: "*"
  cookie-domain: ".company.net"
  whitelist-domain: ".company.net"

  set-xauthrequest: "true" # add x-auth-request-email, x-auth-request-groups, x-auth-request-preferred-username, x-auth-request-user
  pass-access-token: "true" # add x-auth-request-access-token: eyJh...

ingress:
  enabled: true
  path: /oauth2
  hosts:
    - my.company.net
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
```

and here's nexus helm chart's my values.yaml
```yaml
image:
  tag: 3.28.0

nexus:
  dockerSupport:
    enabled: false
  env:
    - name: NEXUS_CONTEXT
      value: nexus-stage

  livenessProbe:
    path: /nexus-stage
  readinessProbe:
    path: /nexus-stage

deployment:
  initContainers:
    - name: init
      image: curlimages/curl:7.72.0
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'https_proxy=http://168.219.61.252:8080 curl -skL -o /opt/sonatype/nexus/deploy/nexus3-keycloak-plugin-0.4.0-bundle.kar https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/v0.4.0/nexus3-keycloak-plugin-0.4.0-bundle.kar']
      volumeMounts:
        - name: nexus-deploy
          mountPath: /opt/sonatype/nexus/deploy
  postStart:
    command: '["/bin/sh", "-c", "cp /sonatype-nexus-conf/keycloak.json /opt/sonatype/nexus/etc/"]'

  additionalVolumes:
    - name: nexus-deploy
      emptyDir: {}
  additionalVolumeMounts:
    - name: nexus-deploy
      mountPath: /opt/sonatype/nexus/deploy

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-preferred-username,x-auth-request-access-token"
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
      auth_request_set $token $upstream_http_x_auth_request_access_token;
      more_set_headers "X-Auth-Username: $preferred_username";
      more_set_headers "X-Auth-Token: $token";
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hostPath: /nexus-stage
  hostRepo: my.company.net
  tls:
    - secretName: ingress-tls

config:
  enabled: true
  data:
    keycloak.json: |
      {
        "realm": "test",
        "auth-server-url": "https://my.company.net/keycloak-stage/",
        "ssl-required": "external",
        "resource": "nexus",
        "credentials": {
          "secret": "d0605dbb-c4d2-45ef-be2d-3491axxxxxxx"
        },
        "confidential-port": 0
      }
```

and I can login manually using my keycloak(oidc)'s id/pw. but SSO does not work.
and I can see the headers like below.
![image](https://user-images.githubusercontent.com/1247030/95969820-2a997180-0e4a-11eb-8000-4feb70ca3cd3.png)

![image](https://user-images.githubusercontent.com/1247030/95960907-52370c80-0e3f-11eb-8ea8-c73b450ad5e8.png)

**Comment by flytreeleft** [comment]
@Hokwang Try to modify you nexus's values.yaml like this:

```yaml
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Auth-Username $upstream_http_x_auth_request_preferred_username;
      proxy_set_header X-Auth-Token $upstream_http_x_auth_request_access_token;
```

**Comment by flytreeleft** [comment]
@Hokwang You can check the Keycloak's log when SSO is failed.

**Comment by Hokwang** [comment]
> @Hokwang Try to modify you nginx's values.yaml like this:

@flytreeleft Thanks for your comment! do you mean nexus's values.yaml?
but I am trying like,
```
  nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
      auth_request_set $token              $upstream_http_x_auth_request_access_token;
      proxy_set_header X-Auth-Username     $upstream_http_x_auth_request_preferred_username;
      proxy_set_header X-Auth-Token        $upstream_http_x_auth_request_access_token;
```

it does not help.

**Comment by flytreeleft** [comment]
@Hokwang Please check the Keycloak's log

**Comment by flytreeleft** [comment]
@Hokwang It maybe is a mistake, the correct yaml should be:

```yaml
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $http_host;
      proxy_set_header X-Auth-Username $preferred_username;
      proxy_set_header X-Auth-Token $token;
```

Please try it again :)

**Comment by Hokwang** [comment]
@flytreeleft 
I can't find any WARN message in keycloak log now, I tested with removing cookies in browser.

I think my ingress-nginx's config is
`use-proxy-protocol: "false"` (default)
so I think `proxy_set_header` does not work, that's why I use `more_set_headers`.

And also nexus's log tells me nothing...

**Comment by Hokwang** [comment]
following your comment, I edited nexus's ingress annotaions,
```
  nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
      auth_request_set $token              $upstream_http_x_auth_request_access_token;
      proxy_set_header Host $http_host;
      proxy_set_header X-Auth-Username     $preferred_username;
      proxy_set_header X-Auth-Token        $token;
```

when I use `proxy_set_header` I can't see x-auth-* and Host in response header in chrome browser.

**Comment by Hokwang** [comment]
@flytreeleft  many thanks for your help.

oh, my got. I found it.

`nginx.ingress.kubernetes.io/enable-cors: "true"` is needed.

after adding this, SSO works!

**Comment by flytreeleft** [comment]
@Hokwang :+1: That's a good news :)

**Comment by flytreeleft** [comment]
@Hokwang And what's your `nginx.ingress.kubernetes.io/configuration-snippet`?

**Comment by Hokwang** [comment]
but another problem is here.
I can't sign out. when I click `sign out` but it retried sign in automatically so logged in continuously....

and like #53 (maybe), few minutes later, (maybe 5 mins)
```
2020-10-14 10:48:29,648+0000 INFO  [qtp1642377476-52] *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo failed: Unexpected response from server: 401 / Unauthorized
org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpResponseException: Unexpected response from server: 401 / Unauthorized
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethod.execute(HttpMethod.java:65)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.http.HttpMethodResponse$2.execute(HttpMethodResponse.java:37)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakAdminClient.obtainUserInfo(KeycloakAdminClient.java:88)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.authenticate(NexusKeycloakClient.java:70)
	at org.github.flytreeleft.nexus3.keycloak.plugin.internal.NexusKeycloakClient.authenticate(NexusKeycloakClient.java:53)
<snip>
```

**Comment by Hokwang** [comment]
my last ingress's annotaions is
```yaml
annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: nexus-stage
    meta.helm.sh/release-namespace: nexus-stage
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-request-preferred-username,x-auth-request-access-token
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
      auth_request_set $token              $upstream_http_x_auth_request_access_token;
      proxy_set_header Host $http_host;
      proxy_set_header X-Auth-Username     $preferred_username;
      proxy_set_header X-Auth-Token        $token;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
```

**Comment by flytreeleft** [comment]
@Hokwang Yes, you can not sign out via Nexus. If you want to do that, you should rewrite the logout action via Nginx's `sub_filter` like [nginx-gateway/vhost.d/nexus3.conf#L46](https://github.com/flytreeleft/nexus3-keycloak-plugin/blob/master/develop/nginx-gateway/vhost.d/nexus3.conf#L46)

**Comment by flytreeleft** [comment]
@Hokwang I did not find the reason why the token was invalidated automatically after some fixed minutes. I'm confused too :(

**Comment by Hokwang** [comment]
ok, I will try `log out` and
find out more clues about `token invalidated`.

Thanks,

**Comment by Hokwang** [comment]
by the way, do you know that you check auth every 5 seconds?
```
2020-10-14 11:04:05,608+0000 INFO  [qtp1642377476-214] *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo for xxx via org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakHttpHeaderAuthToken: true
2020-10-14 11:04:10,623+0000 INFO  [qtp1642377476-259] *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo for xxx via org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakHttpHeaderAuthToken: true
2020-10-14 11:04:15,637+0000 INFO  [qtp1642377476-214] *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo for xxx via org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakHttpHeaderAuthToken: true
2020-10-14 11:04:20,643+0000 INFO  [qtp1642377476-214] *UNKNOWN org.github.flytreeleft.nexus3.keycloak.plugin.KeycloakAuthenticatingRealm - doGetAuthenticationInfo for xxx via org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakHttpHeaderAuthToken: true
```

but this message shows when I open and stay nexus page.

**Comment by flytreeleft** [comment]
@Hokwang The plugin will not check auth periodically. It should be the Kubernetes's application alive checking.

**Comment by IMbiea** [comment]
OK, thanks @Hokwang , funny enough you are on the same issue I am, but with vouch-proxy.

Just like: https://github.com/flytreeleft/nexus3-keycloak-plugin/issues/53, both of us have issues with the approx 5 minute timeout, and then I get re-directed back to the login page in the app, instead of via keycloak (or vouch)  

I can't figure out just yet if it's nexus not happy with the 401, or nginx-ingress not happy with/how to handle the 401 redirect

after 5 minutes I just get the nexus (not keycloak) login page again.

Any further luck on the 5 minute timeout?

**Comment by Hokwang** [comment]
@flytreeleft did you read this article? https://devopstales.github.io/sso/nexus-sso/
Do you have any idea?

current state, I think I have below problem.
1) signout works but not beautiful.
: added sub_filter and then sign out button works to redirect my.company.net/logout just

2) signout works even but no way to login admin

3) few mins after Unauthorized

**Comment by Hokwang** [comment]
after 5 mins (I checked that is 5 minutes, right)
![image](https://user-images.githubusercontent.com/1247030/96068177-4fd3c180-0ed6-11eb-9634-9d1e414a2546.png)
![image](https://user-images.githubusercontent.com/1247030/96068205-64b05500-0ed6-11eb-9254-81a4b0cf2f27.png)

**Comment by flytreeleft** [comment]
@Hokwang You remind me. The token has an expiration time in `org.github.flytreeleft.nexus3.keycloak.plugin.internal.KeycloakTokenManager#updateToken`, maybe it's just the 5 minutes. I will add some debug information for the expiration time and verify that.

**Comment by IMbiea** [comment]
@flytreeleft , to add to that note of the timeout, The issue I have is not so much the 5 minutes, but the fact that when that 5 minutes expires, I get the pop-ups for login at the nexus page, but not a redirect to the oauth proxy.   @Hokwang , is this your behavior as well?

**Comment by flytreeleft** [comment]
@Hokwang @IMbiea Please modify your Nginx configuration as:

```nginx
# https://github.com/vouch/vouch-proxy#installation
server {
    listen 88;
    server_name 172.17.0.1;

    error_log  /var/log/nginx/error.log debug;
    access_log /var/log/nginx/error.log main;

    # Note: replace the following urls to your real services
    set $auth_proxy_root_url "http://172.17.0.1:9090";
    ## For Vouch Proxy, the logout url must be present in the configuration file on the list 'vouch.post_logout_redirect_uris'
    set $auth_keycloak_logout_url "http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/logout";

    # send all requests to the `/validate` endpoint for authorization
    auth_request /validate;

    location = /validate {
        internal;
        proxy_cache off;
        # forward the /validate request to Vouch Proxy
        proxy_pass $auth_proxy_root_url/validate;

        # be sure to pass the original host header
        proxy_set_header Host $http_host;

        # Vouch Proxy only acts on the request headers
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        # these return values are used by the @error401 call
        auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
        auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
        auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    # if validate returns `401 not authorized` then forward the request to the @error401 block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 $auth_proxy_root_url/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    # Set the global variables which will be used in the directive 'sub_filter'
    set $login_path "/login";
    set $logout_path "/logout";

    location = /login {
        return 302 $auth_proxy_root_url/login?url=$scheme://$http_host;
    }

    location = /logout {
        return 302 $auth_proxy_root_url/logout?url=$auth_keycloak_logout_url%3Fredirect_uri%3D$scheme://$http_host;
    }

    # proxy pass authorized requests to your service
    location / {
        # Note: $auth_resp_x_vouch_user actually is the user's email,
        #      the $auth_resp_x_vouch_username is the real user name
        auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
        auth_request_set $auth_resp_x_vouch_username $upstream_http_x_vouch_idp_claims_preferred_username;
        auth_request_set $auth_resp_x_vouch_idp_accesstoken $upstream_http_x_vouch_idp_accesstoken;

        proxy_set_header Host $http_host;
        proxy_set_header X-Keycloak-Sec-Auth $auth_resp_x_vouch_user:$auth_resp_x_vouch_idp_accesstoken;
        proxy_hide_header X-Remote-User-Access-Token;

        client_max_body_size 500M;
        # Disable cache of assets
        proxy_cache            off;
        proxy_read_timeout     600;
        proxy_connect_timeout  600;

        proxy_pass http://172.17.0.1:8903;

        proxy_hide_header WWW-Authenticate;  # Avoid to pop-up the login dialog
        # The script will do:
        # - Inject the action to the logout button, and redirect the page to the logout url after the logout button is clicked
        # - Inject the action to the login button, and redirect the page to the login url after the login button is clicked
        # - Inspect the HTTP status 401, and redirect the page to the login url when the 401 is occurred
        # - Never show the SignIn window any more, because the script will update the authentication automatically by redirecting the page to the login url
        sub_filter '</body>' '<script type="text/javascript">(function inject_logout() { var dom = document.querySelector("a[id^=\'nx-header-signout-\']"); if (!dom) { setTimeout(inject_logout, 200); } else { dom.addEventListener("click", function (event) { event.stopPropagation(); window.location.href = "$logout_path"; }, true); }})(); (function inject_login() { var dom = document.querySelector("a[id^=\'nx-header-signin-\']"); if (!dom) { setTimeout(inject_login, 200); } else { dom.addEventListener("click", function (event) { event.stopPropagation(); window.location.href = "$login_path" + window.location.hash; }, true); }})(); (function inject_401() { if (Ext && Ext.Ajax && Ext.Ajax.onRequestComplete) { var onRequestComplete = Ext.Ajax.onRequestComplete; Ext.Ajax.onRequestComplete = function(a) { if (a && a.result && a.result.status == 401) { window.location.href = "$login_path" + window.location.hash; } else { onRequestComplete.call(this, a); } } } else { setTimeout(inject_401, 200); } })(); (function hide_signin_win() { if (NX && NX.controller && NX.controller.User) { NX.controller.User.prototype.showSignInWindow = function() {} } else { setTimeout(hide_signin_win, 200); } })();</script></body>';
        sub_filter_once on;

        # Just for debugging, you may not want it
        # access_by_lua_block {
        #     ngx.log(ngx.DEBUG, 'auth_resp_x_vouch_user: '..(ngx.var.auth_resp_x_vouch_user or '')..', auth_resp_x_vouch_idp_accesstoken: '..(ngx.var.auth_resp_x_vouch_idp_accesstoken or ''))
        # }
    }
}
```

And, I have verified that the Keycloak token will actually be expired after 5 minutes which is used as the default setting:

![gtkshot](https://user-images.githubusercontent.com/1321315/96335754-62542380-10ad-11eb-8b49-84ee0288c725.png)

With the configuration, you will get:
- Redirect the page to the login/logout url of Keycloak after clicking the login/logout button;
- Automatically refresh the page when the Keycloak token is expired after 5min;
- No login window or dialog will pop-up again;
- And, you can not login or logout with the Nexus's original way, maybe you should set a Keycloak user as the Nexus administration; @Hokwang

**Comment by Hokwang** [comment]
really thank you. this is awesome.

**Comment by IMbiea** [comment]
@Hokwang , maybe because it's with vouch, but would you mind sharing your ingress annotations for this?  I'm debating on some of the global vars with a configmap, but curious what your final product was?

Thanks!

**Comment by IMbiea** [comment]
@Hokwang , did you have to do a custom nginx.tmpl to get this working with your nginx-ingress?

**Comment by Hokwang** [comment]
@IMbiea 
In my case, I choose use RUT, so enabling RUT is needed.
and here's `user can't logout` issue but I think it is fine.
and I did set config as code everything like change admin pw, set keycloak relam, http proxy, set rut, create repo, etc.

and my nexus's values.yaml is
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
      proxy_set_header X-Proxy-REMOTE-USER $preferred_username;
```

simple.

**Comment by IMbiea** [comment]
@Hokwang , thank you.  This portion I have just fine, however I'm uncertain how to correctly setup the use of the subfilter (and login/logout locations via annotations.)... actually I guess the subfilter section is fine (in configuration snippet, but I don't see that you call that in your example)..

**Comment by flytreeleft** [comment]
@IMbiea Try the following configuration, I think it will be fine.

```yaml
ingress:
  enabled: true
  annotations:
    // ...
    nginx.ingress.kubernetes.io/configuration-snippet: |
      // ...
      proxy_hide_header WWW-Authenticate;  # Avoid to pop-up the login dialog
      # The script will do:
      # - Inject the action to the logout button, and redirect the page to the logout url after the logout button is clicked
      # - Inject the action to the login button, and redirect the page to the login url after the login button is clicked
      # - Inspect the HTTP status 401, and redirect the page to the login url when the 401 is occurred
      # - Never show the SignIn window any more, because the script will update the authentication automatically by redirecting the page to the login url
      sub_filter '</body>' '<script type="text/javascript">(function inject_logout() { var dom = document.querySelector("a[id^=\'nx-header-signout-\']"); if (!dom) { setTimeout(inject_logout, 200); } else { dom.addEventListener("click", function (event) { event.stopPropagation(); window.location.href = "$logout_path"; }, true); }})(); (function inject_login() { var dom = document.querySelector("a[id^=\'nx-header-signin-\']"); if (!dom) { setTimeout(inject_login, 200); } else { dom.addEventListener("click", function (event) { event.stopPropagation(); window.location.href = "$login_path" + window.location.hash; }, true); }})(); (function inject_401() { if (Ext && Ext.Ajax && Ext.Ajax.onRequestComplete) { var onRequestComplete = Ext.Ajax.onRequestComplete; Ext.Ajax.onRequestComplete = function(a) { if (a && a.result && a.result.status == 401) { window.location.href = "$login_path" + window.location.hash; } else { onRequestComplete.call(this, a); } } } else { setTimeout(inject_401, 200); } })(); (function hide_signin_win() { if (NX && NX.controller && NX.controller.User) { NX.controller.User.prototype.showSignInWindow = function() {} } else { setTimeout(hide_signin_win, 200); } })();</script></body>';
      sub_filter_once on;
```
